#!/usr/bin/env python3
import os
import sys
import json
import shutil
from datetime import datetime
try:
    import requests
except ImportError:
    print('Please install requests: pip install requests')
    sys.exit(1)

API_URL = os.environ.get('API_URL', 'http://127.0.0.1:7788/products')
SRC_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'products.js')
BACKUP_DIR = os.path.join(os.path.dirname(__file__), '..', 'backups')

os.makedirs(BACKUP_DIR, exist_ok=True)

resp = requests.get(API_URL, timeout=10)
resp.raise_for_status()
obj = resp.json()
products = obj.get('products') or obj.get('Products') or []

if not products:
    print('No products returned from API:', obj)
    sys.exit(1)

# Backup original file
timestamp = datetime.utcnow().strftime('%Y%m%d%H%M%S')
backup_path = os.path.join(BACKUP_DIR, f'products.js.bak.{timestamp}')
shutil.copy2(SRC_PATH, backup_path)
print('Backed up existing products.js to', backup_path)

# Map API products to frontend shape
mapped = []
for idx, p in enumerate(products, start=1):
    name = p.get('ProductName') or p.get('ProductName'.lower()) or p.get('ProductName'.upper()) or p.get('ProductName', '')
    # fallback keys
    name = name or p.get('ProductName') or p.get('ProductName') or p.get('ProductName')
    price = p.get('Price')
    try:
        price = float(price) if price is not None else 0
    except Exception:
        # if price contains currency symbol, strip non-numeric
        import re
        s = str(price)
        num = re.sub(r"[^0-9.]", "", s)
        price = float(num) if num else 0

    mapped.append({
        'id': idx,
        'name': p.get('ProductName') or p.get('ProductName') or p.get('ProductName') or f"Product {idx}",
        'price': price,
        'image': p.get('ImageUrl') or p.get('ImageUrl'.lower()) or '',
        'badge': p.get('Badge') or None,
        'available': (p.get('StockQuantity') is None) and True or (int(p.get('StockQuantity') or 0) > 0),
        'category': p.get('Category') or '',
        'description': p.get('Description') or ''
    })

# Write new JS file
lines = []
lines.append('// This file is auto-generated by scripts/sync_products_from_api.py')
lines.append('')
lines.append('export const products = [')
for p in mapped:
    lines.append('  {')
    lines.append(f"    id: {p['id']},")
    lines.append(f"    name: '{p['name'].replace("'","\\'')}',")
    # keep price as number (no currency formatting)
    if isinstance(p['price'], int) or (isinstance(p['price'], float) and p['price'].is_integer()):
        price_val = int(p['price'])
    else:
        price_val = p['price']
    lines.append(f"    price: {price_val},")
    lines.append(f"    image: '{p['image'].replace("'","\\'')}',")
    if p['badge']:
        lines.append(f"    badge: '{p['badge'].replace("'","\\'')}',")
    lines.append(f"    available: {str(p['available']).lower()},")
    lines.append(f"    category: '{p['category'].replace("'","\\'')}',")
    lines.append(f"    description: '{p['description'].replace("'","\\'')}',")
    lines.append('  },')
lines.append('];')

with open(SRC_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Wrote', SRC_PATH)
print('Updated', len(mapped), 'products.')
